# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

  # Exclude generated and vendor files from linting
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'config/environments/**/*'

# Load additional cops
require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

# Limits for line length
Layout/LineLength:
  Max: 120

# Limits for methods and blocks
Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature']
  Max: 25
